default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  adapter: postgresql
  encoding: unicode
  database: pies_api
  pool: 5
  username: pies_api
  password: hornblower13

development:
  adapter: postgresql
  encoding: unicode
  database: pies_api
  pool: 5
  username: pies_api
  password: hornblower13
